import {
  Archive, Braces, Calculator, CalendarClock, Clock3, CloudDownload, Code2, Crosshair, Database, FileCode, FileCode2, FileSearch, Fingerprint, FlaskConical, Hash,
  Image, Images, KeyRound, Languages, LineChart, Link2, ListChecks, ListFilter, LockKeyhole, Network, PenLine, QrCode, Quote, Radio, Regex,
  ScrollText, Shield, Sigma, Stamp, Table2, TextCursorInput, Type, WandSparkles, Workflow,
} from 'lucide-react'

// Group order and labels follow DevToys (https://devtoys.app/).
export const groups = [
  { id: 'convert', label: 'Converters', icon: Workflow },
  { id: 'text', label: 'Text', icon: TextCursorInput },
  { id: 'encode', label: 'Encoders & decoders', icon: LockKeyhole },
  { id: 'format', label: 'Formatters', icon: Braces },
  { id: 'generate', label: 'Generators', icon: WandSparkles },
  { id: 'graphic', label: 'Graphic', icon: Images },
  { id: 'media', label: 'Media', icon: CloudDownload },
  { id: 'data-playground', label: 'Data Playground', icon: Table2 },
  { id: 'test', label: 'Testers', icon: FlaskConical },
]

export const tools = [
  { id: 'playground-data', name: 'Data', description: 'Load CSV or sample datasets and inspect columns and rows.', category: 'data-playground', icon: Table2, keywords: 'data playground csv upload iris customers dataset preview' },
  { id: 'playground-analyze', name: 'Analyze', description: 'Explore PCA, correlation, similarity, distance, k-means, and statistics.', category: 'data-playground', icon: Sigma, keywords: 'data playground mining pca correlation similarity distance clustering statistics' },
  { id: 'playground-visualize', name: 'Visualize', description: 'Chart your dataset with scatter, histogram, box, line, and bar plots.', category: 'data-playground', icon: LineChart, keywords: 'data playground plot chart scatter histogram box line bar' },
  { id: 'cron', name: 'Cron parser', short: '⏱', description: 'Explain cron expressions and show upcoming runs.', category: 'convert', icon: CalendarClock, keywords: 'crontab schedule expression next runs' },
  { id: 'json-table', name: 'JSON to table', short: 'Tbl', description: 'Turn JSON arrays into tables or CSV.', category: 'convert', icon: Table2, keywords: 'array csv tsv spreadsheet columns rows' },
  { id: 'yaml', name: 'JSON ↔ YAML', short: 'YAML', description: 'Convert between JSON and YAML.', category: 'convert', icon: Languages, keywords: 'configuration parser serializer' },
  { id: 'timestamp', name: 'Timestamp', short: 'UTC', description: 'Convert Unix timestamps and dates.', category: 'convert', icon: Clock3, keywords: 'unix epoch date time seconds milliseconds' },
  { id: 'number-base', name: 'Number base', short: '0x', description: 'Convert integers across common bases.', category: 'convert', icon: Sigma, keywords: 'binary decimal hexadecimal octal bigint' },
  { id: 'calculator', name: 'Calculator', short: '∑', description: 'SpeedCrunch-style scientific calculator with history and constants.', category: 'convert', icon: Calculator, keywords: 'math expression scientific sin cos pi evaluate formula' },
  { id: 'escape', name: 'Escape / unescape', short: '\\n', description: 'Escape or unescape JSON and XML text.', category: 'text', icon: Quote, keywords: 'json javascript xml string escape unescape quote' },
  { id: 'list', name: 'List comparer', short: 'A∩B', description: 'See which lines are shared or unique.', category: 'text', icon: ListChecks, keywords: 'set intersection union difference lines' },
  { id: 'markdown', name: 'Markdown preview', short: 'MD', description: 'Write Markdown and preview the result.', category: 'text', icon: ScrollText, keywords: 'html render preview readme' },
  { id: 'analyzer', name: 'Text analyzer', short: 'Aa', description: 'Inspect and transform text.', category: 'text', icon: Type, keywords: 'word count lines uppercase lowercase sort deduplicate trim' },
  { id: 'compare', name: 'Text comparer', short: '±', description: 'Compare two text blocks at a glance.', category: 'text', icon: ListFilter, keywords: 'diff changes lines words inline side by side' },
  { id: 'base64', name: 'Base64 text', short: 'B64', description: 'Encode or decode text as Base64.', category: 'encode', icon: Code2, keywords: 'base 64 unicode decoder utf8 ascii' },
  { id: 'base64-image', name: 'Base64 image', short: 'Img', description: 'Encode images to Base64 or decode Base64 to a preview.', category: 'encode', icon: Image, keywords: 'picture data url png jpeg gif' },
  { id: 'certificate', name: 'Certificate decoder', short: 'TLS', description: 'Inspect PEM X.509 certificate details.', category: 'encode', icon: Shield, keywords: 'x509 pem ssl tls public key' },
  { id: 'gzip', name: 'GZip', short: 'gz', description: 'Compress text to Base64 GZip or decompress GZip data.', category: 'encode', icon: Archive, keywords: 'compress decompress deflate' },
  { id: 'html', name: 'HTML encoder', short: 'HTML', description: 'Escape markup or decode HTML entities.', category: 'encode', icon: FileCode2, keywords: 'entities escape unescape' },
  { id: 'jwt', name: 'JWT encoder', short: 'JWT', description: 'Encode or decode JSON Web Tokens (HS256/384/512).', category: 'encode', icon: Fingerprint, keywords: 'json web token auth claims sign' },
  { id: 'qrcode', name: 'QR code', short: 'QR', description: 'Generate QR codes from text or read codes from images.', category: 'encode', icon: QrCode, keywords: 'matrix barcode scan decode' },
  { id: 'url', name: 'URL encoder', short: 'URL', description: 'Percent-encode or decode URL data (RFC 3986).', category: 'encode', icon: Link2, keywords: 'uri escape unescape component' },
  { id: 'json', name: 'JSON formatter', short: 'JSON', description: 'Validate, format, minify, or sort JSON.', category: 'format', icon: Braces, keywords: 'pretty print minify validate formatter sort properties jsonc repair quotes comments' },
  { id: 'sql', name: 'SQL formatter', short: 'SQL', description: 'Format SQL for common dialects.', category: 'format', icon: Database, keywords: 'pretty print query mysql postgres tsql' },
  { id: 'xml', name: 'XML formatter', short: 'XML', description: 'Format or minify XML.', category: 'format', icon: FileCode, keywords: 'pretty print minify attributes' },
  { id: 'hash', name: 'Hash generator', short: 'SHA', description: 'Create SHA digests from text or files.', category: 'generate', icon: Hash, keywords: 'checksum sha-1 sha-256 sha-384 sha-512' },
  { id: 'lorem', name: 'Lorem Ipsum', short: '¶', description: 'Generate placeholder text on demand.', category: 'generate', icon: ScrollText, keywords: 'dummy copy paragraphs words' },
  { id: 'password', name: 'Password generator', short: '•••', description: 'Generate strong random passwords.', category: 'generate', icon: KeyRound, keywords: 'secret secure passphrase' },
  { id: 'uuid', name: 'UUID generator', short: 'ID', description: 'Create UUID v1, v4, or v7 identifiers.', category: 'generate', icon: Fingerprint, keywords: 'guid unique identifier v1 v4 v7 hyphens uppercase' },
  { id: 'image-converter', name: 'Image converter', short: 'Img', description: 'Convert images between PNG, JPEG, and WebP.', category: 'graphic', icon: Image, keywords: 'png jpeg jpg webp convert format picture' },
  { id: 'image-watermark', name: 'Image watermark', short: 'WM', description: 'Add tiled text watermarks to photos locally.', category: 'graphic', icon: Stamp, keywords: 'id card stamp overlay opacity text picture' },
  { id: 'image-coordinates', name: 'Image coordinates', short: 'XY', description: 'Pick points or rectangles and copy pixel coordinates.', category: 'graphic', icon: Crosshair, keywords: 'position region bbox markup ui design' },
  { id: 'jsxgraph', name: 'Function graph', short: 'ƒ', description: 'Plot math expressions on an interactive board (pan and zoom).', category: 'graphic', icon: LineChart, keywords: 'jsxgraph graph plot function desmos math curve formula' },
  { id: 'mermaid', name: 'Mermaid diagrams', short: 'MM', description: 'Write Mermaid markup and preview the diagram.', category: 'graphic', icon: Network, keywords: 'mermaid flowchart sequence diagram chart graphviz' },
  { id: 'drawio', name: 'draw.io editor', short: 'IO', description: 'Create and edit diagrams with a self-hosted draw.io editor.', category: 'graphic', icon: PenLine, keywords: 'drawio diagrams.net flowchart wireframe whiteboard' },
  { id: 'cipher', name: 'AES encrypt / decrypt', short: 'AES', description: 'Encrypt or decrypt text with a shared password (AES).', category: 'encode', icon: LockKeyhole, keywords: 'aes password secret share private crypto' },
  { id: 'm3u8', name: 'M3U8 downloader', short: 'HLS', description: 'Download HLS streams with AES-128 support; memory or streaming save.', category: 'media', icon: CloudDownload, keywords: 'hls video ts segment playlist stream' },
  { id: 'jsonpath', name: 'JSONPath tester', short: 'JP', description: 'Query JSON with JSONPath expressions.', category: 'test', icon: Braces, keywords: 'json path query filter selector' },
  { id: 'xml-tester', name: 'XML tester', short: 'XSD', description: 'Validate XML documents against an XSD schema.', category: 'test', icon: FileSearch, keywords: 'xsd schema validate xml' },
  { id: 'regex', name: 'Regex tester', short: '.*', description: 'Test, replace, and extract with JavaScript, Python, Go, Java, .NET, and Rust patterns.', category: 'test', icon: Regex, keywords: 'pattern match capture groups tester flags multiline python golang java rust csharp substitution extraction replace' },
  { id: 'hoppscotch', name: 'Hoppscotch', short: 'API', description: 'Send REST, GraphQL, and WebSocket requests (Postwoman). Works with the Hoppscotch browser extension for CORS.', category: 'test', icon: Radio, keywords: 'hoppscotch postwoman api rest graphql websocket http client request interceptor cors extension' },
]

export const initialSamples = {
  json: '{\n  "project": "supercharger",\n  "active": true,\n  "tools": ["json", "text", "time"]\n}',
  sql: 'select id, name from users where active = 1 order by name;',
  xml: '<catalog><tool id="json">JSON formatter</tool><tool id="sql">SQL formatter</tool></catalog>',
  base64: 'Power up your workflow ⚡',
  url: 'https://example.com/search?q=dev tools&lang=en',
  html: '<h1>Power & speed</h1>',
  jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJicmFkIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjQ3MDAwMDAwMDB9.signature-is-not-verified',
  jwtPayload: '{\n  "sub": "brad",\n  "name": "Brad"\n}',
  jwtSecret: 'supercharger-dev-secret',
  gzip: 'Hello World! é)à',
  certificate: '-----BEGIN CERTIFICATE-----\nMIIE8TCCAtkCFCfJ02eLyJUoeGzsBkJFSjlx5P8jMA0GCSqGSIb3DQEBCwUAMDUx\nCzAJBgNVBAYTAkRUMRMwEQYDVQQIDApTb21lLVN0YXRlMREwDwYDVQQKDAhEZXYg\nVG95czAeFw0yMzA0MTcxNDQwNDhaFw0yNDA0MTYxNDQwNDhaMDUxCzAJBgNVBAYT\nAkRUMRMwEQYDVQQIDApTb21lLVN0YXRlMREwDwYDVQQKDAhEZXYgVG95czCCAiIw\nDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANuTxLYIhWb87/zEdFIa0RhnZd6K\nTq+66yvpT82pN6REZ31bTf7xfNOeArSOWta80AfNCKVCw2UjCi2Qe0e+pNZU6Tjl\nF5LKVnlW0XIT9BiRxxJ3TLAJpBiLeH/O0vikWx4Svlet7DrT3SW7S1CKxyAQF+DG\nvEkH8dzqGyKzj1Yet6FOzY19DrNAcg+3yjm36bRYe24ykJ5wJ7g6v4TTwg4sW8bG\nQDhvDmCMSlj4II7UCFj2w7uK0z1XBHvzsp0cBikQiUpTOvR3MZA4uzFevIPq/GWg\no4Hljp6qhVmYNC3dcjyLQjWyLYMIV3Wtqq2L+VbA6e4/wDw5dCB007RAAQp2dcLH\n/5ybVZ4wZPM8Zsx52Stc4zygDKzrZZop4BhOip1UC1a9HAx39OrlF3B2Vi01VaNM\nztwvhbG4tZahZVKTbckkV9mAtx7c+xTAljx0uaz6fIzvnhziqBokxQQTLmyKAHXP\ndPaomMa/Q5ruapBPfwIw9xgOCzyjDUn11fUO+W074F4V7YfN8aRdoxdasU4c/S3F\nevJZqPsXgQAecETewXFdbX2DFTs8IR/Yz6UHeZaMjjl5g6lVALe/NFvmqp5sLm9T\nZM7haQG3hP9os/El6YXIK9Yyghf/5FdX3xbo8PpY1quoVuM0bgHQOs6M5JGRm02V\nC3zNV0WDSHbVsGh1AgMBAAEwDQYJKoZIhvcNAQELBQADggIBAA+IHRcqvIzjPDGX\nJSQQA/vadD2EmZDfY3HKTxvwXyRfn/9i0R0yKuMuZm9cgexVIHDHeark0PsvkJwh\nY7wXD5uNDq3kXPeHX3+xMLA6skBMYZT2lFBJrwUTGlNnJHBaJfBU+VvKNzDcMfRk\ntp62PJyXP4qfcSGDDruaoqqmvzyaSyOdbsinQmWrxvd0Tio3JjQbD8dZNjc6E0Vl\naTQS7NggdBlt4Yp85k6VXEJFhVVwrJDrRftH7efp6ekT7MivrRQpEfb113gl2xuG\n3JH2xQdFnmL3z5vSlS/ffkGdHUNZPib3CM1w/sG+9DrMK60CVWKVogF3YEg5pp9Q\nOsdEabkiDPwZTDh9tm8cmfVckke7YzpPEw5mqJfsYa9MpwLVMsniCRNpfoZUoFNT\n0kGu19K8+PVkNlhqOfzxaqHnjRIY5wytDY18JecSkmKlg8VSBZft7C3cxni27kxC\nWWrZ6LI8sk0uO+NZPB/68Iz6Qf1VkSVgvDSN7aehpYQq3Gv73CQeJS9tyZ77RSqE\nnqWDyI4+nwJNZN3VURGle1/5XOHNLlFnarVj2r9AGR3P5McwPocWm5Dw5rwf0pXf\npsZA0Q7ZlBVnEArftIGFNa8UoUGR2Lo89gLJsDhqUkCVEy2zxD8FdrxZVdW1KtaT\nixUiDYhfU7a41ebpMlwMfA+QAuK0\n-----END CERTIFICATE-----',
  qrcode: 'https://devtoys.app',
  'number-base': '2026', calculator: '2^10+sin(30)', timestamp: '1760000000', yaml: 'name: supercharger\nfast: true\ntools:\n  - format\n  - convert',
  cron: '0 9 * * 1-5',
  'json-table': '[\n  { "name": "Ada", "role": "engineer", "active": true },\n  { "name": "Lin", "role": "designer", "active": false }\n]',
  analyzer: 'Developer tools should stay out of your way.\n\nMake small tasks feel effortless.',
  markdown: '# Supercharge your workflow\n\nWrite **Markdown** here.\n\n- Fast\n- Local\n\n`console.log("hello")`',
  regex: 'brad@example.com\nalex@invalid\nsam@example.org',
  jsonpath: '{\n  "firstName": "John",\n  "phoneNumbers": [\n    { "type": "iPhone", "number": "0123-4567-8888" },\n    { "type": "home", "number": "0123-4567-8910" }\n  ]\n}',
  'jsonpath-query': '$.phoneNumbers[:1].type',
  'xml-tester-xsd': '<?xml version="1.0" encoding="utf-8"?>\n<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.contoso.com/books" xmlns:xs="http://www.w3.org/2001/XMLSchema">\n  <xs:element name="bookstore">\n    <xs:complexType>\n      <xs:sequence>\n        <xs:element maxOccurs="unbounded" name="book">\n          <xs:complexType>\n            <xs:sequence>\n              <xs:element name="title" type="xs:string" />\n              <xs:element name="price" type="xs:decimal" />\n            </xs:sequence>\n            <xs:attribute name="ISBN" type="xs:string" use="required" />\n          </xs:complexType>\n        </xs:element>\n      </xs:sequence>\n    </xs:complexType>\n  </xs:element>\n</xs:schema>',
  'xml-tester-xml': '<?xml version="1.0" encoding="utf-8"?>\n<bookstore xmlns="http://www.contoso.com/books">\n  <book ISBN="1-861003-11-0">\n    <title>The Autobiography of Benjamin Franklin</title>\n    <price>8.99</price>\n  </book>\n</bookstore>',
  compareLeft: 'The quick brown fox\njumps over the lazy dog.\nSee you soon.',
  compareRight: 'The quick red fox\njumps over the lazy dog!\nSee you later.',
  escape: 'Say "hello"\nnext line',
  listLeft: 'apple\nbanana\ncherry',
  listRight: 'banana\ndate\nCherry',
  cipher: 'Share this note securely with a friend.',
  'cipher-key': 'supercharger-shared-key',
  m3u8: 'https://example.com/stream/index.m3u8',
  jsxgraph: 'sin(x)\ncos(x)',
  mermaid: 'flowchart TD\n  A[Start] --> B{Ready?}\n  B -->|Yes| C[Ship it]\n  B -->|No| D[Fix bugs]\n  D --> B',
}

export const jsxGraphExamples = {
  'Sine & cosine': 'sin(x)\ncos(x)',
  Parabola: 'x^2',
  'Cubic wave': 'x^3 - 3*x',
  'Bell curve': 'exp(-x^2)',
  Hyperbola: '1/x',
}

export const mermaidExamples = {
  'Flowchart': 'flowchart TD\n  A[Start] --> B{Ready?}\n  B -->|Yes| C[Ship it]\n  B -->|No| D[Fix bugs]\n  D --> B',
  'Sequence diagram': 'sequenceDiagram\n  actor User\n  participant App\n  User->>App: Open tool\n  App-->>User: Render diagram',
  'Class diagram': 'classDiagram\n  class Tool {\n    +name: string\n    +run()\n  }\n  class Catalog {\n    +tools: Tool[]\n  }\n  Catalog "1" --> "*" Tool',
  'State diagram': 'stateDiagram-v2\n  [*] --> Draft\n  Draft --> Review: submit\n  Review --> Draft: changes\n  Review --> Published: approve',
  'Gantt chart': 'gantt\n  title Release\n  dateFormat YYYY-MM-DD\n  section Build\n  Code     :a1, 2026-01-01, 7d\n  QA       :after a1, 5d',
  'Pie chart': 'pie showData\n  title Browser share\n  "Chrome" : 62\n  "Safari" : 22\n  "Other" : 16',
}
